### ISSUE TITLE
Генератор случайных чисел

### ISSUE THREAD

**Issue by Morfey216** [avngrd/kekstagram#3]
https://github.com/avngrd/kekstagram/blob/c6de81eb3ee948d67be3f4b97f7ad8b1aa7ddf2c/main.js#L47-L51
1. Внутренние переменные min и max не нужны, т.к. нет необходимости преобразовывать целые числа.
2. Используя Math.ceil(), ты получаешь в результате некорректные финальные данные. Здесь нужно округление вниз. Тогда тебе не придется каждый раз при запуске функции вычитать 1 из длины массива
3. https://github.com/avngrd/kekstagram/blob/c6de81eb3ee948d67be3f4b97f7ad8b1aa7ddf2c/main.js#L55

**Comment by avngrd** [comment]
немного не уверен здесь или правильно исправил

**Comment by Morfey216** [comment]
Нет. Когда я писал, что min и max не нужны, я имел ввиду буквально `Внутренние переменные min и max не нужны, т.к. нет необходимости преобразовывать целые числа.` Ты же просто взял и банально их переименовал
https://github.com/avngrd/kekstagram/blob/0aceba0d33f5aecab332ed52e1966c15745eb4c7/main.js#L48-L52

**Comment by avngrd** [comment]
убрал переменные
