### ISSUE TITLE
Грубые нарушения 

### ISSUE THREAD

**Issue by Morfey216** [avngrd/kekstagram#4]
В коде ниже кроется одна из грубейших ошибок!
https://github.com/avngrd/kekstagram/blob/c6de81eb3ee948d67be3f4b97f7ad8b1aa7ddf2c/main.js#L56

документ в помощь: https://learn.javascript.ru/while-for#tsikl-for

**Comment by avngrd** [comment]
исправил но не уверен

**Comment by Morfey216** [comment]
Хорошо, что не уверен... В строке ниже кроется очень серьезная ошибка
https://github.com/avngrd/kekstagram/blob/cff813c61c3cc6f801ecddf8f81ecc867b13b47c/main.js#L55

**Comment by avngrd** [comment]
исправил
