### ISSUE TITLE
Магические числа

### ISSUE THREAD

**Issue by Morfey216** [avngrd/kekstagram#5]
В коде не должно быть неопознанных чисел. Например, что означают числа 15 и 200 в этом коде https://github.com/avngrd/kekstagram/blob/c6de81eb3ee948d67be3f4b97f7ad8b1aa7ddf2c/main.js#L62
или 2 и 10 здесь https://github.com/avngrd/kekstagram/blob/c6de81eb3ee948d67be3f4b97f7ad8b1aa7ddf2c/main.js#L56
И так везде....
Все числа подобного вида должны быть объявлены как константы и вынесены в начало кода

**Comment by avngrd** [comment]
внес эти числа в консту

**Comment by Morfey216** [comment]
Уже гораздо лучше. Однако все константы принято именовать в верхнем регистре, разделяя отдельные слова знаком подчеркивания. Например, константа https://github.com/avngrd/kekstagram/blob/cff813c61c3cc6f801ecddf8f81ecc867b13b47c/main.js#L3
будет указываться так: `var PHOTOS_NUMBER = 25`

**Comment by avngrd** [comment]
переименовал
